name: Github Fetch
description: Fetches a branch from a github repository
author: https://github.com/arromer
requirements:
  - buildkite-agent
configuration:
  properties:
    s3_url:
      type: string
    use_https_repo_url:
      type: string
public: true
