#!/usr/bin/env bash

set -euo pipefail

main() {
  if git config --get-regexp 'http.*.proxy' > /dev/null; then
    for name in $(git config --name-only --get-regexp 'http.*.proxy'); do
      echo "unset ${name}"
      git config --unset "${name}"
    done
  fi
  if git config --get remote.origin.pushurl > /dev/null; then
    echo "unset remote.origin.pushurl"
    git config --unset remote.origin.pushurl
  fi
  if git config --get remote.origin.lfsurl > /dev/null; then
    echo "unset remote.origin.lfsurl"
    git config --unset remote.origin.lfsurl
  fi
  if git config --get remote.origin.lfspushurl > /dev/null; then
    echo "unset remote.origin.lfspushurl"
    git config --unset remote.origin.lfspushurl
  fi
  git config remote.origin.url "${BUILDKITE_REPO}"
  git config --local --unset url.http://github.com/Canva.insteadof
}

main "$@"
