#!/usr/bin/env bash

set -euo pipefail

SSM_PARAM="${GH_CONTROL_USER_ENV_GITHUB_CHECKOUT_PLUGIN_SSM_PARAM:-${BUILDKITE_PLUGIN_GITHUB_FETCH_SSM_PARAM:-}}"
GITHUB_APP_ID="${GH_CONTROL_USER_ENV_GITHUB_CHECKOUT_PLUGIN_APP_ID:-${BUILDKITE_PLUGIN_GITHUB_FETCH_APP_ID:-${GITHUB_APP_ID:-}}}"
GITHUB_APP_SECRET="${GH_CONTROL_USER_ENV_GITHUB_CHECKOUT_PLUGIN_APP_SECRET:-${BUILDKITE_PLUGIN_GITHUB_FETCH_APP_SECRET:-${GITHUB_APP_SECRET:-}}}"
OUTFILE=$(mktemp)
trap 'rm ${OUTFILE}' EXIT
# Prints an info line to stdout.
log_info() {
  echo "$(date '+[%Y-%m-%d %H:%M:%S]') INFO: $*"
}

# Transforms something like git@github.com:Canva/bla.git to canva__bla
print_repo_checkout_path() {
  local repo_url="$1"
  local repo_dir
  repo_dir=$(grep -Eo '([a-zA-Z0-9-]+\/[a-zA-Z0-9-]+)' <<< "${repo_url}" \
      | tr '[:upper:]' '[:lower:]' \
      | sed 's/\//__/g'
      )
  echo "${repo_dir}"
}

print_canva_origin_from_lambda() {
  log_info "invoking lambda..."
  aws lambda invoke \
      --region us-east-1 \
      --function-name ssm-cache \
      --payload "{\"ssm_param\": \"${SSM_PARAM}\"}" \
      "${OUTFILE}" > /dev/null
  jq -r '.body | fromjson | .message' < "${OUTFILE}"
}

print_canva_origin_from_ssm() {
  log_info "retrieving from SSM"
  aws ssm get-parameter \
      --name "${SSM_PARAM}"\
      --query "Parameter.Value"\
      --output text\
      --region "us-east-1"
}

export_canva_origin_url() {
  local origin_url
  log_info "retrieving SSM param ${SSM_PARAM}"
  origin_url="$(print_canva_origin_from_lambda || print_canva_origin_from_ssm)"
  repo_dir="$(print_repo_checkout_path "${origin_url}")"
  if [[ -n "${BUILDKITE_PLUGIN_GITHUB_FETCH_S3_URL:-}" ]]; then
    export BUILDKITE_PLUGIN_GITHUB_FETCH_S3_URL="${BUILDKITE_PLUGIN_GITHUB_FETCH_S3_URL}/${repo_dir}"
  fi

  log_info "Setting remote ${origin_url}"
  export BUILDKITE_REPO="${origin_url}"
}

export_buildkite_repo() {
  log_info "starting pre-checkout"
  local payload
  payload=$(jq -n --arg AppID "${GITHUB_APP_ID}" \
            --arg SecretId "${GITHUB_APP_SECRET}" \
            '{$AppID, $SecretId}')

  # shellcheck disable=SC2064

  # when running aws cli v2, --cli-binary-format raw-in-base64-out is required
  AWS_PAGER='' aws lambda invoke \
      --region us-east-1 \
      --function-name github-app-token \
      --cli-binary-format raw-in-base64-out \
      --payload "${payload}" \
      "${OUTFILE}"

  local token
  token=$(jq -r '.body' <"${OUTFILE}" | jq -r '.token')

  # Converts repo url from git@github.com:Org/repo to https://x-access-token:token@github.com/Org/repo
  export BUILDKITE_REPO="https://x-access-token:${token}@github.com/${BUILDKITE_REPO#*@github.com:}"
}


main() {
  if [[ -n "${SSM_PARAM:-}" ]]; then
    export_canva_origin_url
  else
    log_info "ssm param not configured skipping"
  fi
  if [[ -n "${GITHUB_APP_ID:-}" ]] && [[ -n "${GITHUB_APP_SECRET:-}" ]]; then
    export_buildkite_repo
  fi
}

main "$@"
